// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ0VYpQHqdZ6N7CtSmgFU8FaBTgxk63y8',
    appId: '1:590534796433:web:7ac5b8d239b0e366010b30',
    messagingSenderId: '590534796433',
    projectId: 'smartsocket-140ce',
    authDomain: 'smartsocket-140ce.firebaseapp.com',
    storageBucket: 'smartsocket-140ce.appspot.com',
    measurementId: 'G-NZ1YK3FF70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYNtZS5FVeJIrcO3wMk_BaT0C3ntaKTjA',
    appId: '1:590534796433:android:672f237d6dd3000b010b30',
    messagingSenderId: '590534796433',
    projectId: 'smartsocket-140ce',
    storageBucket: 'smartsocket-140ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTQi20wOXoUTfJ9dCvym4iDM-6WbSIteQ',
    appId: '1:590534796433:ios:d3edb6aeb42b60bd010b30',
    messagingSenderId: '590534796433',
    projectId: 'smartsocket-140ce',
    storageBucket: 'smartsocket-140ce.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTQi20wOXoUTfJ9dCvym4iDM-6WbSIteQ',
    appId: '1:590534796433:ios:d3edb6aeb42b60bd010b30',
    messagingSenderId: '590534796433',
    projectId: 'smartsocket-140ce',
    storageBucket: 'smartsocket-140ce.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ0VYpQHqdZ6N7CtSmgFU8FaBTgxk63y8',
    appId: '1:590534796433:web:39f21aa799b78bcd010b30',
    messagingSenderId: '590534796433',
    projectId: 'smartsocket-140ce',
    authDomain: 'smartsocket-140ce.firebaseapp.com',
    storageBucket: 'smartsocket-140ce.appspot.com',
    measurementId: 'G-YQLDNPWCZ4',
  );
}
